name: 'Relyance SCI Scan'
inputs:
  access-token:
    description: 'Relyance access token'
    required: true
runs:
  using: "composite"
  steps:      
    - name: Pull and run SCI binary 
      run: |
        echo "Temporarily disabled due to Relyance account expiry"
      shell: bash